export const LIKE_PAINTING = 'LIKE_PAINTING';
export const LIKE_PAINTING_SUCCESS = 'LIKE_PAINTING_SUCCESS';
export const LIKE_PAINTING_ERROR = 'LIKE_PAINTING_ERROR';

export const FETCH_PAINTING_REQUEST = 'FETCH_PAINTING_REQUEST';
export const FETCH_PAINTING_SUCCESS = 'FETCH_PAINTING_SUCCESS';
export const FETCH_PAINTING_ERROR = 'FETCH_PAINTING_ERROR';

export const FETCH_PAINTING_DETAILS_REQUEST = 'FETCH_PAINTING_DETAILS_REQUEST';
export const FETCH_PAINTING_DETAILS_SUCCESS = 'FETCH_PAINTING_DETAILS_SUCCESS';
export const FETCH_PAINTING_DETAILS_ERROR = 'FETCH_PAINTING_DETAILS_ERROR';

export const UPDATE_PAINTING_DETAILS_REQUEST = 'UPDATE_PAINTING_DETAILS_REQUEST';
export const UPDATE_PAINTING_DETAILS_SUCCESS = 'UPDATE_PAINTING_DETAILS_SUCCESS';
export const UPDATE_PAINTING_DETAILS_ERROR = 'UPDATE_PAINTING_DETAILS_ERROR';

export const DELETE_PAINTING_DETAILS_REQUEST = 'DELETE_PAINTING_DETAILS_REQUEST';
export const DELETE_PAINTING_DETAILS_SUCCESS = 'DELETE_PAINTING_DETAILS_SUCCESS';
export const DELETE_PAINTING_DETAILS_ERROR = 'DELETE_PAINTING_DETAILS_ERROR';