export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_USERS_LIKES = 'FETCH_USERS_LIKES';
export const FETCH_USERS_LIKES_SUCCESS = 'FETCH_USERS_LIKES_SUCCESS';
export const FETCH_USERS_LIKES_ERROR = 'FETCH_USERS_LIKES_ERROR';